before_deploy:
  - cd dist

deploy:
  - provider: s3
    revision_type: github
    access_key_id: "AKIAI37XCNC3TUXWWKEA"
    secret_access_key: "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"
    bucket: "myphotobin"
    skip_cleanup: true
    acl: public_read
    region: "us-west-2"
language: node_js
node_js: lts/*

jobs:
  include:
    script:
      - yarn install
      - yarn run build

